/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se;
// for reading the inputs of the user
import java.util.Scanner;
// for reading and display txt files
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;



public class AppCLI {
public static int user_score;
    // this function is for the questions and answers check
    public static int Question_Answer(int number_of_lives, String right_answer, String Answer_user) {
        try {
            if (number_of_lives > 0 && right_answer.equals(Answer_user)) {
                user_score++;
                System.out.println("Congrats you got correct answer :) \nYour score is: " + user_score + "/3 \n");
            } else if (!right_answer.equals(Answer_user)) {
                number_of_lives -= 1;
                System.out.println("Wrong Answer :( you lost a life, now " + number_of_lives + " Left \n");
                if (number_of_lives == 0) {
                    System.out.println("""
                            Sorry you are out of lives!
                            Please try again
                            """);
                }
                return number_of_lives;
            }
        } catch (Exception e) {
            System.out.println("An error occurred: " + e.getMessage());
        }
        return number_of_lives;
    }


    public static void main(String[] args) {


        //Set of the variables
        int command = 1;
        String command1;
        String command2;
        String command3;
        String command4;
        String command5;
        String Answer;
        String rightAnswer;

        System.out.println("""
                Welcome to Buddy Program!
                Get ready to embark on an epic journey
                with your gaming companion. Whether you're
                teaming up for adventure or competing for glory,
                your buddy awaits. Let the games begin!

                Text written by ChatGPT
                press 's' to Start or 'q' to quit
                """);

        Scanner scanner = new Scanner(System.in);
        command1 = scanner.nextLine();


        if (command1.equals("q") || command1.equals("Q")) {
            System.out.println("Thank you for trying Buddy Program!");
            return;
        }

        while (command != 0) {
            int number_of_lives = 2;
            user_score = 0;
            switch (command) {
                case 1:
                    System.out.println("""
                            Instructions:
                            Hi learner! I'll guide you through how this marvelous app works.
                            Here's a step-by-step breakdown:
                            
                            1. Choose your topic of interest.
                            2. Decide if you want a brief overview
                               of the topic or jump straight into the questions.
                            3. In which level of difficulty will you like to play?
                            4. Play and have fun, but keep in mind that
                               you have a limited number of lives. Each
                               mistake costs you a life.
                            5. So, there are two outcomes: either you
                               finish all the questions without losing all
                               your lives and see your gaming results, or
                               you fail and have to start over from step 1.
                            """);
                    break;
                case 2:
                    System.out.println("Chemistry");
                    System.out.println("""
                            Would you like to read a little
                            bit of this topic before the questions?
                            
                            (Y) Yes   (N) No   (Q) quit
                            """);
                    command2 = scanner.nextLine();

                    if (command2.equals("Y") || command2.equals("y")) {
                        String fileName = "src/main/java/de/buw/se/Chemistry.txt";
                        // From this line it was created with the help of ChatGPT
                        try {
                            BufferedReader reader = new BufferedReader(new FileReader(fileName));
                            String line;
                            while ((line = reader.readLine()) != null) {
                                System.out.println(line);
                            }
                            reader.close();
                        } catch (IOException e) {
                            System.err.println("Error reading the file: " + e.getMessage());
                        }
                        // Until this line it  was created with the help of ChatGPT
                    } else if (command2.equals("Q") || command2.equals("q")) {
                        break;
                    }
                    // Here start the game, once we know which level of
                    // difficult wants to have the user
                    System.out.println("""
                            What level of difficulty would
                            you like to face?
                            
                            (1) Beginner  (2) Advance  (Q) Quit
                            """);
                    command3 = scanner.nextLine();

                    if (command3.equals("1")) {
                        System.out.println("Beginner level");
                        System.out.println("""
                                1. What are elements?
                                a) Substances made up of only one type of molecule
                                b) Tiny particles that make up matter
                                c) Special kinds of atoms with unique properties
                                d) Liquids found in nature
                                """);
                        Answer = scanner.nextLine();
                        rightAnswer = "c";
                        number_of_lives = Question_Answer(number_of_lives, rightAnswer, Answer);
                        if (number_of_lives <= 0) {
                            break;
                        }
                        System.out.println("""
                                2. What do atoms join together to form?
                                a) Cells
                                b) Molecules
                                c) Planets
                                d) Stars
                                """);
                        Answer = scanner.nextLine();
                        rightAnswer = "b";
                        number_of_lives = Question_Answer(number_of_lives, rightAnswer, Answer);
                        if (number_of_lives <= 0) {
                            break;
                        }
                        System.out.println("""
                                3. Why is understanding Chemistry important?
                                a) To explore outer space
                                b) To unlock the secrets of the world
                                c) To learn about history
                                d) To study living organisms
                                """);
                        Answer = scanner.nextLine();
                        rightAnswer = "b";
                        number_of_lives = Question_Answer(number_of_lives, rightAnswer, Answer);
                        if (number_of_lives <= 0) {
                            break;
                        }
                    } else if (command3.equals("2")) {
                        System.out.println("Advance level");
                        System.out.println("""
                                1. Which of the following is an example of a change in matter
                                   mentioned in the paragraph?
                                a) Photosynthesis
                                b) Oxidation
                                c) Freezing of water
                                d) Combustion
                                """);
                        Answer = scanner.nextLine();
                        rightAnswer = "c";
                        number_of_lives = Question_Answer(number_of_lives, rightAnswer, Answer);
                        if (number_of_lives <= 0) {
                            break;
                        }
                        System.out.println("""
                                2. What is the composition of water molecules?
                                a) One hydrogen atom and one oxygen atom
                                b) Two hydrogen atoms and one oxygen atom
                                c) Two oxygen atoms and one hydrogen atom
                                d) Two hydrogen atoms and two oxygen atoms
                                """);
                        Answer = scanner.nextLine();
                        rightAnswer = "b";
                        number_of_lives = Question_Answer(number_of_lives, rightAnswer, Answer);
                        if (number_of_lives <= 0) {
                            break;
                        }
                        System.out.println("""
                                3. Which process is an example of a chemical change?
                                a) Water boiling into steam
                                b) Melting of ice
                                c) Burning of wood
                                d) Cutting a piece of paper
                                """);
                        Answer = scanner.nextLine();
                        rightAnswer = "c";
                        number_of_lives = Question_Answer(number_of_lives, rightAnswer, Answer);
                        if (number_of_lives <= 0) {
                            break;
                        }
                    } else if (command3.equals("q") || command3.equals("Q")) {
                        break;
                    }
                    break;
                case 3:
                    System.out.println("History");
                    System.out.println("""
                            Would you like to read a little
                            bit of this topic before the questions?
                            
                            (Y) Yes   (N) No   (Q) quit
                            """);

                    command4 = scanner.nextLine();

                    if (command4.equals("Y") || command4.equals("y")) {
                        String historyText = "src/main/java/de/buw/se/History Topic.txt";
                        try {
                            BufferedReader reader = new BufferedReader(new FileReader(historyText));
                            String line;
                            while ((line = reader.readLine()) != null) {
                                System.out.println(line);
                            }
                            reader.close();
                        } catch (IOException e) {
                            System.err.println("Error reading the file: " + e.getMessage());
                        }
                    } else if (command4.equals("Q") || command4.equals("q")) {
                        break;
                    }

                    System.out.println("""
                            What level of difficulty would
                            you like to face?
                            
                            (1) Beginner  (2) Advance  (Q) Quit
                            """);
                    command5 = scanner.nextLine();

                    if (command5.equals("1")) {
                        System.out.println("Beginner level");
                        System.out.println("""
                                1. What is history?
                                a) The study of the future
                                b) The study of the past
                                c) The study of the present
                                d) The study of fiction
                                """);
                        Answer = scanner.nextLine();
                        rightAnswer = "b";
                        number_of_lives = Question_Answer(number_of_lives, rightAnswer, Answer);
                        if (number_of_lives <= 0) {
                            break;
                        }
                        System.out.println("""
                                2. Which ancient civilization built the pyramids?
                                a) Ancient Greece
                                b) Ancient Rome
                                c) Ancient Egypt
                                d) Ancient China
                                """);
                        Answer = scanner.nextLine();
                        rightAnswer = "c";
                        number_of_lives = Question_Answer(number_of_lives, rightAnswer, Answer);
                        if (number_of_lives <= 0) {
                            break;
                        }
                        System.out.println("""
                                3. What was the main economic system in the Middle Ages?
                                a) Capitalism
                                b) Socialism
                                c) Feudalism
                                d) Mercantilism
                                """);
                        Answer = scanner.nextLine();
                        rightAnswer = "c";
                        number_of_lives = Question_Answer(number_of_lives, rightAnswer, Answer);
                        if (number_of_lives <= 0) {
                            break;
                        }
                    } else if (command5.equals("2")) {
                        System.out.println("Advance level");
                        System.out.println("""
                                1. What were some achievements of ancient civilizations like
                                   Mesopotamia and Egypt?
                                a) Advancements in agriculture and irrigation
                                b) Invention of the wheel
                                c) Development of writing systems
                                d) All of the above
                                """);
                        Answer = scanner.nextLine();
                        rightAnswer = "d";
                        number_of_lives = Question_Answer(number_of_lives, rightAnswer, Answer);
                        if (number_of_lives <= 0) {
                            break;
                        }
                        System.out.println("""
                                2. During the Middle Ages, what was the role of knights in feudal society?
                                a) They were merchants who traded goods across Europe
                                b) They were skilled craftsmen who built castles and cathedrals
                                c) They were warriors who served lords in exchange for land
                                d) They were scholars who preserved ancient texts and knowledge
                                """);
                        Answer = scanner.nextLine();
                        rightAnswer = "c";
                        number_of_lives = Question_Answer(number_of_lives, rightAnswer, Answer);
                        if (number_of_lives <= 0) {
                            break;
                        }
                        System.out.println("""
                                3. How did the Industrial Revolution change society in the 18th and
                                   19th centuries?
                                a) It led to the decline of cities and the rise of rural communities
                                b) It increased the demand for skilled labor and improved living standards
                                c) It resulted in the spread of feudalism and the weakening of monarchies
                                d) It caused a decrease in technological innovation and scientific progress
                                """);
                        Answer = scanner.nextLine();
                        rightAnswer = "b";
                        number_of_lives = Question_Answer(number_of_lives, rightAnswer, Answer);
                        if (number_of_lives <= 0) {
                            break;
                        }

                    }
            }
            System.out.println("""
                    So player enter in which category
                    would you like to play ?
                    
                    0. Quit
                    1. General Information
                    2. Chemistry
                    3. History
                    """);
            command = Integer.parseInt(scanner.nextLine());

        }
        scanner.close();
        System.out.println("Thank you for trying Buddy Program!");
    }
}